from . import res_partner
from . import hotel_room_category
from . import hotel_room
from . import hotel_room_service
from . import hotel_room_service_order
from . import hotel_reservation
from . import hotel_reservation_guest
from . import hotel_reservation_feedback
from . import hotel_reservation_package
from . import hotel_housekeeping