{
    'name': 'Hotel Management',
    'version': '18.0.1.6.4',
    'category': 'Services',
    'summary': 'Reservations, rooms, housekeeping, F&B, events, guest portal',
    'depends': ['base', 'mail', 'website', 'portal', 'account', 'calendar'],
    'data': [
        'security/hotel_security.xml',
        'security/ir.model.access.csv',
        'security/hotel_record_rules.xml',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/hotel_room_categories.xml',
        'data/hotel_products.xml',
        'data/hotel_venue_data.xml',
        'views/hotel_room_views.xml',
        'views/hotel_reservation_views.xml',
        'views/hotel_checkin_wizard_views.xml',
        'views/hotel_housekeeping_views.xml',
        'views/hotel_room_service_views.xml',
        'views/hotel_dashboard_views.xml',
        'views/hotel_venue_views.xml',
        'views/hotel_event_views.xml',
        'views/hotel_menus.xml',
        'views/website_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'hotel_management/static/src/js/hotel_date_widgets.js',
            'hotel_management/static/src/js/hotel_dashboard.js',
            'hotel_management/static/src/xml/hotel_dashboard.xml',
            'hotel_management/static/src/scss/hotel_dashboard.scss',
        ],
    },
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}